CREATE SEQUENCE SEQ_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_GM_USUARIO (
  id_usuario          NUMBER DEFAULT SEQ_USUARIO.NEXTVAL PRIMARY KEY,
  nm_usuario          VARCHAR2(100) NOT NULL,
  nm_email            VARCHAR2(100) NOT NULL,
  nm_senha            VARCHAR2(100) NOT NULL,
  st_tipo_usuario     VARCHAR2(100) DEFAULT 'USER'
);  

ALTER TABLE T_GM_USUARIO ADD CONSTRAINT UNQ_NM_EMAIL UNIQUE (nm_email);